<a href="https://colab.research.google.com/github/atulpatil2228/Pw_ML_learning/blob/main/8_Data_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## data encoding >> converting categorical columns into numeric
## Nominal /OHE
## Label and ordinal encoding
## Target guided ordinal encoding


In [2]:
## Nominal OHE >> Binary vector for each of the categories
## example single ,married, sepreated
## single:[1,0,0]
## married : [0,1,0]
## seprated : [0,0,1]


In [34]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({'status':['single','married','seprated','single','married']})

In [35]:
df

status
0    single
1   married
2  seprated
3    single
4   married

In [5]:
encoder = OneHotEncoder()

In [6]:
encoder

OneHotEncoder()

In [8]:
encoded = encoder.fit_transform(df[['status']]).toarray()

In [9]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [10]:
encoder.get_feature_names_out()

array(['status_married', 'status_seprated', 'status_single'], dtype=object)

In [12]:
encoder_df  = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [13]:
encoder_df

status_married  status_seprated  status_single
0             0.0              0.0            1.0
1             1.0              0.0            0.0
2             0.0              1.0            0.0
3             0.0              0.0            1.0
4             1.0              0.0            0.0

In [15]:
encoder.transform([['single']]).toarray()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [18]:
pd.concat([df,encoder_df],axis = 1)

status  status_married  status_seprated  status_single
0    single             0.0              0.0            1.0
1   married             1.0              0.0            0.0
2  seprated             0.0              1.0            0.0
3    single             0.0              0.0            1.0
4   married             1.0              0.0            0.0

In [20]:
import seaborn as sns
df = sns.load_dataset('tips')

In [21]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [27]:
encoded = encoder.fit_transform(df[['time']]).toarray()

In [29]:
encoder.get_feature_names_out()

array(['time_Dinner', 'time_Lunch'], dtype=object)

In [30]:
encoder_df  = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [31]:
encoder_df

time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]

In [37]:
## label encoding >> assign unique label to the categories
## using map or usng library

In [38]:
df

status
0    single
1   married
2  seprated
3    single
4   married

In [39]:
from sklearn.preprocessing import LabelEncoder
Label_Encoder = LabelEncoder()

In [43]:
Label_Encoder.fit_transform(df[['status']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [44]:
Label_Encoder.transform([['seprated']])

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [45]:
## ordinal encoding

## High School : 1
## graduation : 2
## post graduate : 3
## phd : 4

In [46]:
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({'qualification':['HS','GR','PG','PHD','HS','PHD']})

In [47]:
df

qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5           PHD

In [48]:
encoder = OrdinalEncoder(categories=[['HS','GR','PG','PHD']])

In [49]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [50]:
## new data
encoder.transform([['PG']])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [51]:
## target guided ordinal encoding
## relationship with target varaible
## lot of unique categories are there
## replace the category with mean and median of respective group

In [52]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [53]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [55]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [56]:
df['time_encodec'] = df['time'].map(mean_price)

In [57]:
df

time  total_bill  time_encodec
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333