In [1]:
#data encoding >> converting categorical columns into numeric
## nominal /OHE
## Label and ordinal enncoding 
## Target guided ordinal encoding


In [2]:
## Nominal/OHE>> it creaters binary vector for each categories
## exaple: single ,married, seprated
# single :[1,0,0]
#married ;[0,1,0]
## seprated:[0,0,1]

In [3]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
df = pd.DataFrame({'status':['single','married','separated','single','single','married','married']})

In [7]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [8]:
encoder = OneHotEncoder()

In [9]:
encoder

OneHotEncoder()

In [12]:
encoded = encoder.fit_transform(df[['status']]).toarray()

In [14]:
encoder_df = pd.DataFrame(encoded,columns = encoder.get_feature_names_out())

In [15]:
encoder_df

status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             0.0               0.0            1.0
5             1.0               0.0            0.0
6             1.0               0.0            0.0

In [17]:
## new data
encoder.transform([['single']]).toarray()

C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [18]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [22]:
pd.concat([df ,encoder_df],axis=1)

status  status_married  status_separated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4     single             0.0               0.0            1.0
5    married             1.0               0.0            0.0
6    married             1.0               0.0            0.0

In [24]:
## label encoding >> assigns unique label to categories

In [25]:
df

status
0     single
1    married
2  separated
3     single
4     single
5    married
6    married

In [26]:
from sklearn.preprocessing import LabelEncoder

In [30]:
label_encoder = LabelEncoder

In [34]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['status_encoded'] = label_encoder.fit_transform(df['status'])  # not df[['status']]


In [35]:
label_encoder

LabelEncoder()

In [36]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()  # create an instance
df['status_encoded'] = label_encoder.fit_transform(df['status'])  # use instance


In [37]:
df['status_encoded']

0    2
1    0
2    1
3    2
4    2
5    0
6    0
Name: status_encoded, dtype: int64

In [38]:
label_encoder.transform([['single']])

C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [39]:
label_encoder.transform([['separated']])

C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [40]:
## ordinal encoding 
## highschool ;1
## college ;2
## pg ; 3
## phd ; 4

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [45]:
df = pd.DataFrame({'qualification': ['HS','GR','PG','PHd','HS','HS','PG','PHd','PG']})
df

qualification
0            HS
1            GR
2            PG
3           PHd
4            HS
5            HS
6            PG
7           PHd
8            PG

In [51]:
encoder = OrdinalEncoder(categories=[['HS','GR','PG','PHd']])

In [52]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [0.],
       [2.],
       [3.],
       [2.]])

In [53]:
## new data
encoder.transform([['PHd']])

C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[3.]])

In [54]:
## Target guided oridnal encoding
## relatioship with arget variable
## A lot of unique categories 
## replace the categories with mean and median of respective target groups

In [61]:
df = pd.DataFrame({'time':['lunch','dinner','breakfast','lunch','dinner','breakfast'],
             'total_bill':[120,130,90,125,150,190]})

In [60]:
df

time  total_bill
0      lunch         120
1     dinner         130
2  breakfast          90
3      lunch         125
4     dinner         150
5  breakfast         190

In [65]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [66]:
mean_price

{'breakfast': 140.0, 'dinner': 140.0, 'lunch': 122.5}

In [ ]:
df['time_encoded']